"""initial_schema

Revision ID: a64d56880497
Revises: 
Create Date: 2026-06-16 15:30:08.806273

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a64d56880497'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('headline', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('current_title', sa.String(length=256), nullable=True),
    sa.Column('current_company', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('years_of_experience', sa.Float(), nullable=True),
    sa.Column('preferred_work_mode', sa.String(length=64), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=True)
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('experience_years_min', sa.Integer(), nullable=True),
    sa.Column('experience_years_max', sa.Integer(), nullable=True),
    sa.Column('salary_min_lpa', sa.Float(), nullable=True),
    sa.Column('salary_max_lpa', sa.Float(), nullable=True),
    sa.Column('must_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nice_to_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hard_disqualifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('acceptable_locations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('company_size', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_history_candidate_id'), 'career_history', ['candidate_id'], unique=False)
    op.create_table('certifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('issuing_organization', sa.String(length=256), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certifications_candidate_id'), 'certifications', ['candidate_id'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=256), nullable=True),
    sa.Column('degree', sa.String(length=256), nullable=True),
    sa.Column('field_of_study', sa.String(length=256), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_candidate_id'), 'education', ['candidate_id'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('proficiency', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_candidate_id'), 'languages', ['candidate_id'], unique=False)
    op.create_table('ranking_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phase1_runtime_seconds', sa.Float(), nullable=True),
    sa.Column('phase2_runtime_seconds', sa.Float(), nullable=True),
    sa.Column('total_candidates_read', sa.Integer(), nullable=True),
    sa.Column('valid_candidates', sa.Integer(), nullable=True),
    sa.Column('honeypots_detected', sa.Integer(), nullable=True),
    sa.Column('consulting_only_disqualified', sa.Integer(), nullable=True),
    sa.Column('non_technical_disqualified', sa.Integer(), nullable=True),
    sa.Column('candidates_scored', sa.Integer(), nullable=True),
    sa.Column('score_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weights_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=256), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranking_runs_job_description_id'), 'ranking_runs', ['job_description_id'], unique=False)
    op.create_table('redrob_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('open_to_work_flag', sa.Boolean(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('recruiter_response_rate', sa.Float(), nullable=True),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('interview_completion_rate', sa.Float(), nullable=True),
    sa.Column('offer_acceptance_rate', sa.Float(), nullable=True),
    sa.Column('verified_email', sa.Boolean(), nullable=False),
    sa.Column('verified_phone', sa.Boolean(), nullable=False),
    sa.Column('linkedin_connected', sa.Boolean(), nullable=False),
    sa.Column('github_activity_score', sa.Float(), nullable=True),
    sa.Column('saved_by_recruiters_30d', sa.Integer(), nullable=False),
    sa.Column('profile_completeness_score', sa.Float(), nullable=True),
    sa.Column('expected_salary_min_lpa', sa.Float(), nullable=True),
    sa.Column('expected_salary_max_lpa', sa.Float(), nullable=True),
    sa.Column('skill_assessment_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redrob_signals_candidate_id'), 'redrob_signals', ['candidate_id'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('proficiency', sa.String(length=32), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('endorsements', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_candidate_id'), 'skills', ['candidate_id'], unique=False)
    op.create_table('candidate_ranks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ranking_run_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.String(length=300), nullable=True),
    sa.Column('semantic_skill_fit', sa.Float(), nullable=True),
    sa.Column('experience_quality', sa.Float(), nullable=True),
    sa.Column('career_progression', sa.Float(), nullable=True),
    sa.Column('behavioral_signals', sa.Float(), nullable=True),
    sa.Column('logistics_fit', sa.Float(), nullable=True),
    sa.Column('profile_integrity', sa.Float(), nullable=True),
    sa.Column('disqualifier_multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ranking_run_id'], ['ranking_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_ranks_candidate_id'), 'candidate_ranks', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_ranks_ranking_run_id'), 'candidate_ranks', ['ranking_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_ranks_ranking_run_id'), table_name='candidate_ranks')
    op.drop_index(op.f('ix_candidate_ranks_candidate_id'), table_name='candidate_ranks')
    op.drop_table('candidate_ranks')
    op.drop_index(op.f('ix_skills_candidate_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_redrob_signals_candidate_id'), table_name='redrob_signals')
    op.drop_table('redrob_signals')
    op.drop_index(op.f('ix_ranking_runs_job_description_id'), table_name='ranking_runs')
    op.drop_table('ranking_runs')
    op.drop_index(op.f('ix_languages_candidate_id'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_education_candidate_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_certifications_candidate_id'), table_name='certifications')
    op.drop_table('certifications')
    op.drop_index(op.f('ix_career_history_candidate_id'), table_name='career_history')
    op.drop_table('career_history')
    op.drop_table('job_descriptions')
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
